name: Update Stars

on:
  push:
    branches: [master]
  schedule:
    - cron: '22 22 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            stars
            data
          key: ${{ runner.os }}-stars-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-stars-

      - run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            stars
            data
          key: ${{ runner.os }}-stars-${{ github.run_number }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
          message: 'chore: autopublish [skip ci]'
